name = input("Hey there! Please enter your name: \n")
instruction = (" Welcome to the Band Name Generator!!! \nI will help you generate your band name")
print("Hello " + name + instruction)
pet = input("Whats the name of your pet (If you have any) : \n")
print("Your band name can be: " + name + pet)
